{
 "title": "Kubernetes / Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "tags": [ "kubernetes-pase" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "节点信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "节点在线率",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"}) / sum(kube_node_info)"
    }
   ]
  },
  {
   "title": "节点状态统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition}}"
    }
   ]
  },
  {
   "title": "节点角色统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_role{}) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Kubelet版本",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_node_info{}) by (kubelet_version)",
     "legendFormat": "{{ kubelet_version}}"
    }
   ]
  },
  {
   "title": "异常节点数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info)-sum(kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "不可调度节点数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "CPU使用率最高的容器TOP 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m])) by (namespace, instancepod_name, container_name))",
     "legendFormat": "{{namespace}} | {{ container_name }} in {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod内存使用Top 5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_usage_bytes{job=\"kubelet\",name=~\"^k8s_.*\"}) by (namespace,pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Pod信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pod异常数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\",job=\"kube-state-metrics\"} == 1)"
    }
   ]
  },
  {
   "title": "Pod Unready数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((kube_pod_status_ready{condition=\"true\",job=\"kube-state-metrics\"} == 0)  + on (namespace,pod)  (kube_pod_status_phase{phase!=\"Succeeded\",job=\"kube-state-metrics\"} == 1))"
    }
   ]
  },
  {
   "title": "Pod未调度数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_unschedulable{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pod状态统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pod重启次数(15m)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(round(delta(kube_pod_container_status_restarts_total[15m]) > 0))"
    }
   ]
  },
  {
   "title": "Pod正在重启",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(round(delta(kube_pod_container_status_restarts_total{}[15m]))>0) by (pod,namespace)"
    }
   ]
  },
  {
   "title": "Pod总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_pod_info)" }
   ]
  },
  {
   "title": "Container总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_pod_container_info)" }
   ]
  },
  {
   "title": "异常Pod信息",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\",job=\"kube-state-metrics\"}  == 1) by (namespace,pod)"
    },
    {
     "expr": "max(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\",job=\"kube-state-metrics\"} ==1 ) by (namespace,phase,pod)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "max(kube_pod_container_status_terminated_reason{job=\"kube-state-metrics\",reason!=\"Completed\"} ==1 ) by (namespace,reason,pod)",
     "legendFormat": "term-{{reason}}"
    },
    {
     "expr": "label_replace((max(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\"} ==1 ) by (namespace,reason,pod)),\"wait_reason\", \"$1\", \"reason\", \"(.*)\")",
     "legendFormat": "{{wait_reason}}"
    },
    {
     "expr": "max(kube_pod_status_unschedulable{job=\"kube-state-metrics\"}) by (namespace,pod)"
    }
   ]
  },
  {
   "title": "Unready的Pod信息",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "(kube_pod_status_ready{condition=\"true\",job=\"kube-state-metrics\"} == 0)  +  on(namespace,pod)   group_right   sum(kube_pod_status_phase{phase!=\"Succeeded\",job=\"kube-state-metrics\"} == 1) by (namespace,pod,phase)\r"
    },
    {
     "expr": "max(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\",job=\"kube-state-metrics\"} ==1 ) by (namespace,phase,pod)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "max(kube_pod_container_status_terminated_reason{job=\"kube-state-metrics\",reason!=\"Completed\"} ==1 ) by (namespace,reason,pod)",
     "legendFormat": "term-{{reason}}"
    },
    {
     "expr": "label_replace((max(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\"} ==1 ) by (namespace,reason,pod)),\"wait_reason\", \"$1\", \"reason\", \"(.*)\")",
     "legendFormat": "{{wait_reason}}"
    }
   ]
  },
  {
   "title": "最近1天内发生重启 TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right sum(kube_pod_container_status_last_terminated_reason{service=\"kube-state-metrics\"}==1) by (namespace,pod,container,reason)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(kube_pod_container_resource_limits_memory_bytes{service=\"kube-state-metrics\"}) by (pod,container,namespace)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(pod_container:container_memory_working_set_bytes{service=\"kubelet\"}) by (pod,container,namespace)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(pod_container:container_memory_max_usage_bytes{service=\"kubelet\"}) by (pod,container,namespace)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(pod_container:container_memory_usage_bytes{service=\"kubelet\"}) by (pod,container,namespace)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(pod_container:container_memory_rss{service=\"kubelet\"}) by (pod,container,namespace)"
    },
    {
     "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{service=\"kube-state-metrics\"}[1d])) by (namespace,pod,container) >0 ) +  on(namespace,pod,container)   group_right max(pod_container:container_memory_cache{service=\"kubelet\"}) by (pod,container,namespace)"
    }
   ]
  },
  { "title": "常用资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Deployment总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_deployment_created{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Deployment 副本总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{job=\"kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "Deployment 活跃副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "StateFulset 当前副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "StateFulset 异常副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{job=\"kube-state-metrics\"})  - sum(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "Job数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_job_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Job当前活跃数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Job异常数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Deployment 无副本数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas{job=\"kube-state-metrics\"}==0)"
    }
   ]
  },
  {
   "title": "Deployment 异常数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_status_condition{condition=\"Available\",status=\"true\",job=\"kube-state-metrics\"} == 0)"
    }
   ]
  },
  {
   "title": "Deployment 无效副本数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "StateFulset总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_statefulset_created{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "StateFulset 副本总数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{job=\"kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "PVC请求总容量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 49 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{job=\"kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "PVC异常数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_status_phase{phase=~\"Failed|Pending\",job=\"kube-state-metrics\"} == 1)"
    }
   ]
  },
  {
   "title": "PV异常数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{phase=~\"Failed|Pending\",job=\"kube-state-metrics\"} == 1)"
    }
   ]
  },
  {
   "title": "PVC状态统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_persistentvolumeclaim_status_phase{}) by (phase)",
     "legendFormat": "pvc-{{ phase }}"
    },
    {
     "expr": "sum (kube_persistentvolume_status_phase{}) by (phase)",
     "legendFormat": "pv-{{ phase}}"
    }
   ]
  },
  {
   "title": "DaemonSet状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{job=\"kube-state-metrics\"}) by(namespace,daemonset)"
    },
    {
     "expr": "sum(kube_daemonset_status_number_misscheduled{job=\"kube-state-metrics\"}) by(namespace,daemonset)"
    },
    {
     "expr": "sum(kube_daemonset_status_number_unavailable{job=\"kube-state-metrics\"}) by(namespace,daemonset)"
    },
    {
     "expr": "sum(kube_daemonset_status_current_number_scheduled{job=\"kube-state-metrics\"}) by(namespace,daemonset)"
    },
    {
     "expr": "sum(kube_daemonset_status_number_ready{job=\"kube-state-metrics\"}) by(namespace,daemonset)"
    }
   ]
  }
 ]
}